"""Pentest Report Generator -- Convert PentestReport to professional Markdown.

Generates:
- Executive Summary
- Severity breakdown with counts
- Detailed findings with remediation
- Phase timeline
"""

from __future__ import annotations

from datetime import datetime, timezone

from src.intelligence.pentest import Finding, PentestReport, Severity
from src.utils.logging import get_logger

log = get_logger("intelligence.report_gen")

_SEVERITY_EMOJI: dict[str, str] = {
    "CRITICAL": "!!",
    "HIGH": "!",
    "MEDIUM": "~",
    "LOW": ".",
    "INFO": " ",
}

_SCORE_DESCRIPTIONS: dict[str, str] = {
    "A": "Excellent -- No significant vulnerabilities found.",
    "B": "Good -- Minor issues detected, low risk.",
    "C": "Fair -- Some medium-severity issues need attention.",
    "D": "Poor -- High-severity vulnerabilities present.",
    "F": "Critical -- Critical vulnerabilities require immediate action.",
}


class ReportGenerator:
    """Generate professional pentest reports in Markdown."""

    @staticmethod
    def generate_markdown(report: PentestReport) -> str:
        """Generate full Markdown pentest report."""
        lines: list[str] = []
        now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        # Header
        lines.append(f"# Pentest Report: {report.target}")
        lines.append("")
        lines.append(f"**Date:** {now_utc}")
        lines.append(f"**Scope:** {report.scope}")
        lines.append(f"**Duration:** {report.duration_ms}ms ({report.duration_ms / 1000:.1f}s)")
        lines.append(f"**Security Score:** {report.score}")
        lines.append("")

        # Executive Summary
        lines.append("## Executive Summary")
        lines.append("")
        by_sev = report.findings_by_severity
        total = len(report.all_findings)
        lines.append(
            f"Scanned **{report.target}** across {len(report.phases)} phases. "
            f"Found **{total}** findings:"
        )
        lines.append("")
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for sev in Severity:
            count = len(by_sev[sev.value])
            if count > 0:
                lines.append(f"| {sev.value} | **{count}** |")
        lines.append("")

        # Score explanation
        score = report.score
        score_desc = _SCORE_DESCRIPTIONS.get(score, "")
        lines.append(f"**Overall: {score} -- {score_desc}**")
        lines.append("")

        # Detailed Findings (grouped by severity)
        lines.append("## Detailed Findings")
        lines.append("")

        finding_num = 0
        for sev in Severity:
            sev_findings = by_sev[sev.value]
            if not sev_findings:
                continue
            lines.append(f"### {sev.value} ({len(sev_findings)})")
            lines.append("")
            for f in sev_findings:
                finding_num += 1
                _append_finding(lines, finding_num, f)

        # Phase Timeline
        lines.append("## Phase Timeline")
        lines.append("")
        lines.append("| Phase | Duration | Findings | Errors |")
        lines.append("|-------|----------|----------|--------|")
        for phase in report.phases:
            lines.append(
                f"| {phase.name} | {phase.duration_ms}ms "
                f"| {len(phase.findings)} | {len(phase.errors)} |"
            )
        lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by JARVIS Pentest Pipeline -- {now_utc}*")

        return "\n".join(lines)

    @staticmethod
    def generate_summary(report: PentestReport) -> str:
        """Generate short summary for Telegram/CLI output."""
        findings = report.all_findings
        by_sev = report.findings_by_severity

        parts: list[str] = [f"Pentest: {report.target}"]
        parts.append(
            f"Score: {report.score} | {len(findings)} findings | "
            f"{report.duration_ms / 1000:.1f}s"
        )
        parts.append("")

        for sev in Severity:
            count = len(by_sev[sev.value])
            if count > 0:
                parts.append(f"  {sev.value}: {count}")

        # Top 5 critical/high findings
        important = by_sev["CRITICAL"] + by_sev["HIGH"]
        if important:
            parts.append("")
            parts.append("Top Issues:")
            for f in important[:5]:
                parts.append(f"  [{f.severity.value}] {f.title}")

        return "\n".join(parts)


def _append_finding(lines: list[str], num: int, f: Finding) -> None:
    """Append a single finding to the report lines."""
    lines.append(f"#### {num}. {f.title}")
    lines.append("")
    lines.append(f"- **Severity:** {f.severity.value}")
    lines.append(f"- **Tool:** `{f.tool}`")
    lines.append(f"- **Phase:** {f.phase}")
    lines.append(f"- **Description:** {f.description}")
    if f.evidence:
        lines.append("")
        lines.append("**Evidence:**")
        lines.append("```")
        lines.append(f.evidence[:1000])
        lines.append("```")
    if f.remediation:
        lines.append("")
        lines.append(f"**Remediation:** {f.remediation}")
    lines.append("")
