#!/usr/bin/env python3
"""Supplementary training data for JARVIS Brain 14B.

Adds ~250 records focused on weak categories and more diverse coverage.
"""
import json
from pathlib import Path

SYSTEM = "Bạn là JARVIS — trợ lý AI cá nhân thông minh."
OUTPUT = Path(__file__).parent.parent / "training" / "data" / "processed" / "curated_v3_sft.jsonl"


def rec(user: str, assistant: str, category: str) -> dict:
    return {
        "messages": [
            {"role": "system", "content": SYSTEM},
            {"role": "user", "content": user},
            {"role": "assistant", "content": assistant},
        ],
        "metadata": {"category": category, "curated": True, "version": "v3"},
    }


def math_advanced() -> list[dict]:
    return [
        rec("Tính đạo hàm của f(x) = x^3 + 2x^2 - 5x + 3", "f'(x) = 3x² + 4x - 5\n\n**Áp dụng công thức:**\n- d/dx(x³) = 3x²\n- d/dx(2x²) = 4x\n- d/dx(-5x) = -5\n- d/dx(3) = 0\n\nVậy f'(x) = 3x² + 4x - 5", "math"),
        rec("Giải phương trình bậc 2: x² - 5x + 6 = 0", "Dùng công thức: x = (-b ± √(b²-4ac)) / 2a\n\na=1, b=-5, c=6\nΔ = 25 - 24 = 1\n\nx₁ = (5 + 1) / 2 = 3\nx₂ = (5 - 1) / 2 = 2\n\n**Nghiệm: x = 2 hoặc x = 3**\n\nKiểm tra: 2² - 5(2) + 6 = 0 ✓ | 3² - 5(3) + 6 = 0 ✓", "math"),
        rec("Tính tích phân ∫(2x + 3)dx", "∫(2x + 3)dx = x² + 3x + C\n\n**Giải thích:**\n- ∫2x dx = 2 × (x²/2) = x²\n- ∫3 dx = 3x\n- C là hằng số tích phân\n\nVậy kết quả: **x² + 3x + C**", "math"),
        rec("100 factorial có bao nhiêu chữ số 0 ở cuối?", "Số chữ số 0 cuối = số lần 10 là thừa số = min(số thừa số 2, số thừa số 5)\n\nĐếm thừa số 5 trong 100!:\n- ⌊100/5⌋ = 20\n- ⌊100/25⌋ = 4\n- ⌊100/125⌋ = 0\n\nTổng = 20 + 4 = **24 chữ số 0**\n\n(Thừa số 2 luôn nhiều hơn 5, nên chỉ cần đếm 5)", "math"),
        rec("Fibonacci thứ 10 là bao nhiêu?", "Dãy Fibonacci: mỗi số = tổng 2 số trước\n\n```\nF(1)  = 1\nF(2)  = 1\nF(3)  = 2\nF(4)  = 3\nF(5)  = 5\nF(6)  = 8\nF(7)  = 13\nF(8)  = 21\nF(9)  = 34\nF(10) = 55\n```\n\n**Fibonacci thứ 10 = 55**", "math"),
        rec("Xác suất tung 2 xúc xắc được tổng = 7?", "Tổng trường hợp: 6 × 6 = 36\n\nCác cặp cho tổng = 7:\n- (1,6), (2,5), (3,4), (4,3), (5,2), (6,1)\n→ 6 trường hợp thuận lợi\n\n**P(tổng = 7) = 6/36 = 1/6 ≈ 16.67%**\n\nĐây là tổng có xác suất cao nhất khi tung 2 xúc xắc!", "math"),
        rec("Big O notation: O(n log n) có nghĩa là gì?", "**O(n log n)** — Quasilinear complexity:\n\n- Tăng nhanh hơn linear O(n) nhưng chậm hơn quadratic O(n²)\n- Phổ biến trong: Merge Sort, Quick Sort (average), Heap Sort\n\n**So sánh với n = 1000:**\n- O(n) = 1,000\n- O(n log n) ≈ 10,000\n- O(n²) = 1,000,000\n\n**Ứng dụng:** Hầu hết thuật toán sort tối ưu đều O(n log n)", "math"),
        rec("Tính diện tích tam giác có 3 cạnh a=3, b=4, c=5", "Dùng công thức Heron:\n\ns = (a+b+c)/2 = (3+4+5)/2 = 6\n\nS = √(s(s-a)(s-b)(s-c))\nS = √(6 × 3 × 2 × 1)\nS = √36 = **6**\n\n(Đây là tam giác vuông 3-4-5, nên cũng có thể tính: S = (3×4)/2 = 6)", "math"),
        rec("Logarithm: log₂(256) = ?", "log₂(256) = ?\n\nTìm x sao cho 2^x = 256:\n- 2¹ = 2\n- 2² = 4\n- 2⁴ = 16\n- 2⁸ = 256\n\n**log₂(256) = 8**\n\n(256 = 2⁸, nên log base 2 = 8)", "math"),
        rec("Ma trận 2x2: tính determinant [[3,7],[1,5]]", "det(A) = ad - bc\n\nA = |3  7|\n    |1  5|\n\ndet = (3)(5) - (7)(1) = 15 - 7 = **8**\n\nVì det ≠ 0, ma trận này khả nghịch (invertible).", "math"),
    ]


def analysis() -> list[dict]:
    return [
        rec("So sánh Python và JavaScript", "**Python vs JavaScript:**\n\n| Tiêu chí | Python | JavaScript |\n|---|---|---|\n| Cú pháp | Rõ ràng, indent-based | C-style, linh hoạt |\n| Typing | Dynamic (có type hints) | Dynamic (có TypeScript) |\n| Backend | Django, FastAPI, Flask | Node.js, Express, Nest |\n| Frontend | Không phổ biến | Dominant (React, Vue) |\n| ML/AI | Dominant (PyTorch, TF) | Đang phát triển |\n| Speed | Chậm hơn (interpreted) | Nhanh hơn (V8 engine) |\n| Package | pip (PyPI) | npm (largest registry) |\n\n**Chọn Python nếu:** ML/AI, data science, scripting, backend\n**Chọn JS nếu:** Full-stack web, frontend, real-time apps", "analysis"),
        rec("Phân tích ưu nhược điểm của microservices", "**Microservices Architecture:**\n\n**Ưu điểm:**\n- Scale độc lập từng service\n- Team tự chủ, deploy riêng\n- Fault isolation (1 service crash không ảnh hưởng hệ thống)\n- Tech flexibility (service A dùng Python, B dùng Go)\n\n**Nhược điểm:**\n- Complexity tăng (network latency, distributed tracing)\n- Data consistency khó (eventual consistency)\n- DevOps overhead (monitoring, logging, deployment)\n- Debugging phức tạp hơn monolith\n\n**Khi nào dùng:**\n- Team > 10 devs, nhiều domain khác nhau\n- Cần scale từng phần riêng\n- Chấp nhận complexity overhead\n\n**Khi nào KHÔNG dùng:**\n- MVP, startup nhỏ, team < 5", "analysis"),
        rec("So sánh SQL vs NoSQL", "**SQL vs NoSQL:**\n\n| | SQL | NoSQL |\n|---|---|---|\n| Schema | Fixed (table, rows) | Flexible (document, key-value) |\n| Scaling | Vertical (scale up) | Horizontal (scale out) |\n| ACID | Có (strong consistency) | Hạn chế (eventual consistency) |\n| Joins | Native | Không hoặc hạn chế |\n| Ví dụ | PostgreSQL, MySQL | MongoDB, Redis, Cassandra |\n\n**Chọn SQL:** Financial data, complex queries, relationships\n**Chọn NoSQL:** Big data, flexible schema, real-time, caching", "analysis"),
        rec("Phân tích trend AI 2025-2026", "**AI Trends 2025-2026:**\n\n1. **Small Language Models (SLMs)**: Qwen3, Phi-4, Gemma — chạy local trên consumer hardware\n2. **Agentic AI**: Agents tự thực hiện task phức tạp (coding, research, planning)\n3. **Multimodal AI**: Text + Image + Audio + Video trong 1 model\n4. **RAG maturity**: Better retrieval, hybrid search, knowledge graphs\n5. **AI Coding Assistants**: GitHub Copilot, Claude Code, Cursor — thay đổi workflow dev\n6. **Open-source dominance**: Qwen, Llama, Mistral cạnh tranh closed models\n7. **Edge AI**: Inference trên mobile/IoT devices\n8. **AI Safety**: Alignment, red teaming, governance frameworks\n\nXu hướng chung: AI ngày càng nhỏ hơn, mạnh hơn, chạy local được.", "analysis"),
        rec("Review code này: for i in range(len(lst)): total += lst[i]", "**Code Review:**\n\n```python\n# ❌ Anti-pattern: indexing trong loop\nfor i in range(len(lst)):\n    total += lst[i]\n\n# ✅ Pythonic: iterate trực tiếp\ntotal = sum(lst)\n\n# Hoặc nếu cần logic phức tạp:\nfor item in lst:\n    total += item\n```\n\n**Vấn đề:**\n1. `range(len())` là anti-pattern trong Python\n2. Indexing `lst[i]` chậm hơn direct iteration\n3. Có built-in `sum()` cho task này\n\n**Tổng kết:** Dùng `sum(lst)` — ngắn gọn, nhanh, Pythonic.", "analysis"),
        rec("Giải thích CAP theorem", "**CAP Theorem** — chỉ chọn được 2/3:\n\n- **C**onsistency: Mọi read nhận được write mới nhất\n- **A**vailability: Mọi request nhận response (không lỗi)\n- **P**artition tolerance: Hệ thống hoạt động dù network split\n\n**Thực tế:** Partition luôn xảy ra → chọn CP hoặc AP:\n\n| Hệ thống | Loại | Ví dụ |\n|---|---|---|\n| CP | Consistency > Availability | PostgreSQL, MongoDB (default) |\n| AP | Availability > Consistency | Cassandra, DynamoDB, CouchDB |\n\n**Tip:** Hầu hết ứng dụng cần eventual consistency (AP) là đủ.", "analysis"),
        rec("Đánh giá FastAPI vs Django", "**FastAPI vs Django:**\n\n| | FastAPI | Django |\n|---|---|---|\n| Type | Modern async framework | Full-stack framework |\n| Speed | Rất nhanh (async/await) | Trung bình |\n| Admin | Không có | Built-in admin panel |\n| ORM | Không (dùng SQLAlchemy) | Django ORM built-in |\n| Auth | Tự implement | Built-in |\n| API docs | Auto (Swagger/ReDoc) | DRF add-on |\n| Learning | Dễ | Trung bình |\n\n**Chọn FastAPI:** API-only, microservices, performance-critical\n**Chọn Django:** Full-stack web, CMS, rapid prototyping, admin-heavy apps", "analysis"),
        rec("SOLID principles là gì?", "**SOLID** — 5 nguyên tắc OOP:\n\n**S** — Single Responsibility: 1 class = 1 nhiệm vụ\n**O** — Open/Closed: Mở để extend, đóng để modify\n**L** — Liskov Substitution: Subclass thay thế được parent\n**I** — Interface Segregation: Interface nhỏ, specific\n**D** — Dependency Inversion: Depend on abstractions, not concretions\n\n**Ví dụ DI:**\n```python\n# ❌ Tight coupling\nclass OrderService:\n    def __init__(self):\n        self.db = PostgresDB()  # Concrete\n\n# ✅ Dependency Inversion\nclass OrderService:\n    def __init__(self, db: Database):  # Abstract\n        self.db = db\n```", "analysis"),
    ]


def factual_expanded() -> list[dict]:
    return [
        rec("Dân số Việt Nam bao nhiêu?", "Theo số liệu gần nhất, dân số Việt Nam khoảng **100 triệu người** (2024), đứng thứ 15 thế giới.\n\n- Diện tích: ~331,000 km²\n- Thủ đô: Hà Nội\n- TP lớn nhất: TP. Hồ Chí Minh\n- GDP/capita: ~4,300 USD (2024)\n- Tuổi thọ trung bình: ~75 năm", "factual"),
        rec("Python ra đời năm nào?", "Python được tạo bởi **Guido van Rossum** và phát hành lần đầu năm **1991**.\n\n- Python 2.0: 2000 (EOL 2020)\n- Python 3.0: 2008\n- Python 3.13: 2024 (latest stable)\n\nTên \"Python\" lấy từ show hài Monty Python, không phải con rắn 🐍", "factual"),
        rec("TCP và UDP khác nhau thế nào?", "**TCP vs UDP:**\n\n| | TCP | UDP |\n|---|---|---|\n| Connection | Connection-oriented | Connectionless |\n| Reliability | Guaranteed delivery | Best-effort |\n| Ordering | In-order | No guarantee |\n| Speed | Chậm hơn (handshake) | Nhanh hơn |\n| Header | 20 bytes | 8 bytes |\n| Use case | Web, email, file transfer | Streaming, gaming, DNS |\n\n**TCP:** Khi cần reliable delivery (HTTP, SSH)\n**UDP:** Khi cần speed, chấp nhận packet loss (VoIP, live stream)", "factual"),
        rec("Docker là gì?", "**Docker** — platform containerization:\n\n- **Container**: Lightweight, isolated environment chạy app\n- **Image**: Template để tạo container (read-only layers)\n- **Dockerfile**: Script build image\n- **Docker Compose**: Quản lý multi-container\n\n```bash\n# Chạy container\ndocker run -p 8080:80 nginx\n\n# Build image\ndocker build -t myapp .\n\n# Docker Compose\ndocker compose up -d\n```\n\n**Ưu điểm:** Portable, consistent, lightweight (vs VM), easy scaling", "factual"),
        rec("REST API là gì?", "**REST** (Representational State Transfer) — kiến trúc API:\n\n**HTTP Methods:**\n- `GET /users` — Lấy danh sách users\n- `POST /users` — Tạo user mới\n- `PUT /users/1` — Cập nhật user 1\n- `DELETE /users/1` — Xóa user 1\n\n**Principles:**\n1. Stateless (mỗi request độc lập)\n2. Client-Server separation\n3. Uniform interface (resource-based URLs)\n4. Cacheable responses\n\n**Status Codes:**\n- 200: OK | 201: Created\n- 400: Bad Request | 404: Not Found\n- 500: Server Error", "factual"),
        rec("Git rebase và merge khác nhau sao?", "**Git Merge vs Rebase:**\n\n**Merge:**\n- Tạo merge commit mới\n- Giữ nguyên history\n- An toàn cho shared branches\n```bash\ngit checkout main\ngit merge feature\n```\n\n**Rebase:**\n- Viết lại history (linear)\n- Clean history, không merge commits\n- CHỈ dùng cho local/private branches\n```bash\ngit checkout feature\ngit rebase main\n```\n\n**Rule:** Merge cho public branches, Rebase cho private branches. KHÔNG rebase commits đã push!", "factual"),
        rec("Kubernetes là gì?", "**Kubernetes (K8s)** — container orchestration:\n\n**Core concepts:**\n- **Pod**: Nhóm 1+ containers\n- **Service**: Network endpoint cho pods\n- **Deployment**: Quản lý replica + rolling update\n- **Namespace**: Logical isolation\n\n**Key features:**\n- Auto-scaling (HPA)\n- Self-healing (restart failed pods)\n- Load balancing\n- Rolling updates + rollback\n- Service discovery\n\n**Khi nào dùng:** Nhiều microservices, cần auto-scaling, multi-team. Overkill cho small apps.", "factual"),
        rec("OAuth 2.0 hoạt động thế nào?", "**OAuth 2.0** — Authorization framework:\n\n**Flow (Authorization Code):**\n1. User click \"Login with Google\"\n2. Redirect → Google consent screen\n3. User approve → Google gửi `authorization_code`\n4. App exchange code → `access_token` (server-side)\n5. App dùng token gọi Google API\n\n**Roles:**\n- Resource Owner (user)\n- Client (app)\n- Authorization Server (Google)\n- Resource Server (Google API)\n\n**Token types:**\n- Access Token: Short-lived, gọi API\n- Refresh Token: Long-lived, lấy access token mới", "factual"),
        rec("Blockchain hoạt động thế nào?", "**Blockchain** — distributed ledger technology:\n\n**Cấu trúc:**\n```\nBlock N-1 → Block N → Block N+1\n[prev_hash] [prev_hash] [prev_hash]\n[timestamp] [timestamp] [timestamp]\n[txs...]    [txs...]    [txs...]\n[nonce]     [nonce]     [nonce]\n[hash]      [hash]      [hash]\n```\n\n**Đặc điểm:**\n- Immutable: Không thể sửa block cũ\n- Decentralized: Không có central authority\n- Consensus: PoW (Bitcoin) hoặc PoS (Ethereum)\n- Transparent: Ai cũng xem được\n\n**Use cases:** Cryptocurrency, supply chain, DeFi, NFT", "factual"),
        rec("WebSocket khác HTTP thế nào?", "**HTTP vs WebSocket:**\n\n| | HTTP | WebSocket |\n|---|---|---|\n| Connection | Request-Response | Full-duplex, persistent |\n| Direction | Client → Server | Bi-directional |\n| Overhead | Headers mỗi request | 1 handshake, sau đó minimal |\n| State | Stateless | Stateful |\n| Use case | REST APIs, web pages | Chat, live updates, gaming |\n\n**WebSocket handshake:**\n```\nGET /ws HTTP/1.1\nUpgrade: websocket\nConnection: Upgrade\n```\n\n**Khi nào dùng:** Real-time apps (chat, notifications, stock tickers)", "factual"),
    ]


def coding_patterns() -> list[dict]:
    return [
        rec("Viết decorator trong Python", "```python\nimport functools\n\ndef timer(func):\n    @functools.wraps(func)\n    def wrapper(*args, **kwargs):\n        import time\n        start = time.perf_counter()\n        result = func(*args, **kwargs)\n        elapsed = time.perf_counter() - start\n        print(f\"{func.__name__} took {elapsed:.4f}s\")\n        return result\n    return wrapper\n\n@timer\ndef slow_function():\n    import time\n    time.sleep(1)\n    return \"done\"\n```\n\n`@functools.wraps` giữ metadata (name, docstring) của function gốc.", "coding"),
        rec("Viết async/await trong Python", "```python\nimport asyncio\n\nasync def fetch_data(url: str) -> str:\n    # Simulate async I/O\n    await asyncio.sleep(1)\n    return f\"Data from {url}\"\n\nasync def main():\n    # Run concurrently\n    results = await asyncio.gather(\n        fetch_data(\"https://api1.com\"),\n        fetch_data(\"https://api2.com\"),\n        fetch_data(\"https://api3.com\"),\n    )\n    for r in results:\n        print(r)\n\nasyncio.run(main())\n```\n\n`asyncio.gather()` chạy multiple coroutines song song — tổng time ≈ 1s thay vì 3s.", "coding"),
        rec("Context manager trong Python", "```python\nfrom contextlib import contextmanager\n\n# Class-based\nclass DatabaseConnection:\n    def __enter__(self):\n        self.conn = create_connection()\n        return self.conn\n    \n    def __exit__(self, exc_type, exc_val, exc_tb):\n        self.conn.close()\n        return False  # Don't suppress exceptions\n\n# Generator-based (simpler)\n@contextmanager\ndef db_connection():\n    conn = create_connection()\n    try:\n        yield conn\n    finally:\n        conn.close()\n\n# Usage\nwith db_connection() as conn:\n    conn.execute(\"SELECT 1\")\n```", "coding"),
        rec("Viết unit test với pytest", "```python\nimport pytest\n\ndef add(a: int, b: int) -> int:\n    return a + b\n\ndef divide(a: float, b: float) -> float:\n    if b == 0:\n        raise ValueError(\"Cannot divide by zero\")\n    return a / b\n\n# Tests\ndef test_add():\n    assert add(2, 3) == 5\n    assert add(-1, 1) == 0\n\ndef test_divide():\n    assert divide(10, 2) == 5.0\n    assert divide(7, 2) == 3.5\n\ndef test_divide_by_zero():\n    with pytest.raises(ValueError, match=\"Cannot divide by zero\"):\n        divide(1, 0)\n\n# Run: pytest test_math.py -v\n```", "coding"),
        rec("Dataclass trong Python", "```python\nfrom dataclasses import dataclass, field\nfrom datetime import datetime\n\n@dataclass\nclass User:\n    name: str\n    email: str\n    age: int = 0\n    tags: list[str] = field(default_factory=list)\n    created_at: datetime = field(default_factory=datetime.now)\n\n    def is_adult(self) -> bool:\n        return self.age >= 18\n\n# Usage\nuser = User(\"Bi\", \"bi@example.com\", 25)\nprint(user)  # User(name='Bi', email='bi@example.com', age=25, ...)\nprint(user.is_adult())  # True\n```\n\nDataclass auto-generates `__init__`, `__repr__`, `__eq__`.", "coding"),
        rec("Type hints trong Python", "```python\nfrom typing import Optional\nfrom collections.abc import Sequence\n\ndef greet(name: str, greeting: str = \"Hello\") -> str:\n    return f\"{greeting}, {name}!\"\n\ndef first_or_none(items: Sequence[int]) -> int | None:\n    return items[0] if items else None\n\ndef process(\n    data: dict[str, list[int]],\n    callback: callable[[int], bool] | None = None,\n) -> list[int]:\n    results = []\n    for values in data.values():\n        for v in values:\n            if callback is None or callback(v):\n                results.append(v)\n    return results\n```\n\nType hints giúp IDE autocomplete và mypy type checking.", "coding"),
        rec("List comprehension vs generator", "```python\n# List comprehension — tạo list trong memory\nsquares = [x**2 for x in range(1000)]\n# → List 1000 items, stored in RAM\n\n# Generator expression — lazy evaluation\nsquares_gen = (x**2 for x in range(1000))\n# → Generates items on-demand, minimal RAM\n\n# Dict comprehension\nword_lengths = {w: len(w) for w in [\"hello\", \"world\"]}\n# → {'hello': 5, 'world': 5}\n\n# Nested comprehension\nflat = [x for row in matrix for x in row]\n\n# With condition\nevens = [x for x in range(20) if x % 2 == 0]\n```\n\n**Rule:** Dùng generator cho data lớn, list cho data nhỏ cần reuse.", "coding"),
        rec("Error handling best practices Python", "```python\nimport logging\n\nlogger = logging.getLogger(__name__)\n\n# Custom exception\nclass NotFoundError(Exception):\n    def __init__(self, resource: str, id: int):\n        self.resource = resource\n        self.id = id\n        super().__init__(f\"{resource} #{id} not found\")\n\ndef get_user(user_id: int) -> dict:\n    try:\n        result = db.query(user_id)\n        if not result:\n            raise NotFoundError(\"User\", user_id)\n        return result\n    except ConnectionError:\n        logger.exception(\"Database connection failed\")\n        raise  # Re-raise, don't swallow\n    except NotFoundError:\n        raise  # Let caller handle\n    except Exception:\n        logger.exception(\"Unexpected error\")\n        raise\n```\n\n**Rules:** Catch specific exceptions, always log, never silently swallow.", "coding"),
        rec("Python pathlib cheat sheet", "```python\nfrom pathlib import Path\n\n# Create paths\np = Path(\"/home/user/docs\")\np = Path.home() / \"docs\"  # Cross-platform\n\n# Navigate\np.parent          # /home/user\np.name             # docs\np.stem             # file (without ext)\np.suffix           # .txt\n\n# Check\np.exists()\np.is_file()\np.is_dir()\n\n# Read/Write\ncontent = p.read_text(encoding=\"utf-8\")\np.write_text(\"hello\", encoding=\"utf-8\")\n\n# Glob\nfor py in Path(\".\").rglob(\"*.py\"):\n    print(py)\n\n# Create dirs\np.mkdir(parents=True, exist_ok=True)\n```\n\nLuôn dùng `pathlib` thay `os.path` — cleaner API!", "coding"),
        rec("f-string formatting tricks", "```python\nname = \"JARVIS\"\npi = 3.14159\ncount = 42\n\n# Padding\nf\"{name:>20}\"     # Right-align, width 20\nf\"{name:<20}\"     # Left-align\nf\"{name:^20}\"     # Center\n\n# Numbers\nf\"{pi:.2f}\"       # 3.14\nf\"{count:05d}\"    # 00042\nf\"{count:,}\"      # 42 (with thousands separator)\nf\"{1000000:_}\"    # 1_000_000\n\n# Debug (Python 3.8+)\nf\"{name=}\"        # name='JARVIS'\nf\"{2+3=}\"         # 2+3=5\n\n# Datetime\nfrom datetime import datetime\nnow = datetime.now()\nf\"{now:%Y-%m-%d %H:%M}\"  # 2026-03-06 19:00\n```", "coding"),
    ]


def devops_expanded() -> list[dict]:
    return [
        rec("Viết Dockerfile cho Python app", "```dockerfile\n# Multi-stage build\nFROM python:3.13-slim AS builder\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n\nFROM python:3.13-slim\nWORKDIR /app\nCOPY --from=builder /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages\nCOPY . .\n\nEXPOSE 8000\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]\n```\n\n**Best practices:**\n- Multi-stage build (giảm image size)\n- COPY requirements.txt trước code (cache layers)\n- `--no-cache-dir` giảm disk usage\n- Non-root user cho security", "devops"),
        rec("GitHub Actions CI/CD cơ bản", "```yaml\n# .github/workflows/ci.yml\nname: CI\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-python@v5\n        with:\n          python-version: '3.13'\n      - run: pip install -r requirements.txt\n      - run: pytest tests/ -v\n\n  lint:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: pip install ruff\n      - run: ruff check .\n```", "devops"),
        rec("Nginx reverse proxy config", "```nginx\n# /etc/nginx/conf.d/myapp.conf\nupstream app_servers {\n    server 127.0.0.1:8000;\n    server 127.0.0.1:8001;\n}\n\nserver {\n    listen 80;\n    server_name myapp.com;\n\n    # Redirect HTTP → HTTPS\n    return 301 https://$server_name$request_uri;\n}\n\nserver {\n    listen 443 ssl;\n    server_name myapp.com;\n\n    ssl_certificate /etc/ssl/certs/myapp.crt;\n    ssl_certificate_key /etc/ssl/private/myapp.key;\n\n    location / {\n        proxy_pass http://app_servers;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n    }\n\n    location /ws {\n        proxy_pass http://app_servers;\n        proxy_http_version 1.1;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection \"upgrade\";\n    }\n}\n```", "devops"),
        rec("Linux troubleshooting commands", "**System:**\n```bash\ntop / htop          # CPU, memory usage\nfree -h             # RAM usage\ndf -h               # Disk usage\ndu -sh /path        # Directory size\nuptime              # System uptime, load\n```\n\n**Network:**\n```bash\nss -tlnp            # Listening ports\ncurl -v URL         # HTTP debug\ndig domain.com      # DNS lookup\ntraceroute host     # Network path\n```\n\n**Process:**\n```bash\nps aux | grep name  # Find process\nkill -9 PID         # Force kill\nlsof -i :8080       # Who uses port 8080\nstrace -p PID       # System calls\n```\n\n**Logs:**\n```bash\njournalctl -u nginx --since \"1 hour ago\"\ntail -f /var/log/syslog\ndmesg | tail        # Kernel messages\n```", "devops"),
        rec("SSH key setup và best practices", "```bash\n# Generate key (Ed25519 — recommended)\nssh-keygen -t ed25519 -C \"your@email.com\"\n\n# Copy to server\nssh-copy-id user@server\n\n# SSH config (~/.ssh/config)\nHost myserver\n    HostName 192.168.1.100\n    User admin\n    IdentityFile ~/.ssh/id_ed25519\n    Port 22\n\n# Connect\nssh myserver\n```\n\n**Security:**\n- Disable password auth (`PasswordAuthentication no`)\n- Use key-based auth only\n- Change default port (optional)\n- Use `fail2ban` chống brute-force\n- Keep keys with passphrase", "devops"),
    ]


def conversation_extended() -> list[dict]:
    return [
        rec("Hôm nay trời đẹp quá", "Thật vậy sao! 🌤️ Ngày đẹp trời thì thật tuyệt để đi dạo hoặc ngồi cafe. Bạn có kế hoạch gì cho ngày hôm nay không?", "conversation"),
        rec("Tôi đang stress quá", "Tôi hiểu cảm giác đó. 💙 Stress là điều bình thường, nhưng đừng quên chăm sóc bản thân:\n\n1. Nghỉ ngơi 5-10 phút\n2. Hít thở sâu\n3. Đi bộ nhẹ\n4. Nói chuyện với ai đó\n\nNếu muốn chia sẻ, tôi luôn ở đây lắng nghe. Bạn có muốn kể tôi nghe chuyện gì không?", "conversation"),
        rec("Gợi ý phim hay đi", "Một vài phim hay cho bạn:\n\n**Sci-Fi:**\n- Interstellar (2014) — Du hành không gian, cảm động\n- Ex Machina (2015) — AI và nhân tính\n- Arrival (2016) — Ngôn ngữ và thời gian\n\n**Action:**\n- John Wick (2014-2024) — Hành động mãn nhãn\n- Top Gun: Maverick (2022) — Bay lượn đỉnh cao\n\n**Drama:**\n- Parasite (2019) — Xã hội Hàn Quốc\n- The Shawshank Redemption (1994) — Classic\n\nBạn thích thể loại nào? Tôi có thể gợi ý thêm! 🎬", "conversation"),
        rec("Tôi muốn học lập trình, bắt đầu từ đâu?", "Lộ trình cho người mới:\n\n**Tháng 1-2: Python cơ bản**\n- Biến, kiểu dữ liệu, vòng lặp\n- Functions, OOP cơ bản\n- Resource: Python.org tutorial, Codecademy\n\n**Tháng 3-4: Projects nhỏ**\n- Calculator, to-do app, web scraper\n- Học Git + GitHub\n\n**Tháng 5-6: Chọn hướng**\n- Web: FastAPI/Django + HTML/CSS/JS\n- Data: Pandas, NumPy, Matplotlib\n- AI/ML: PyTorch, scikit-learn\n\n**Tips:**\n- Code mỗi ngày (dù chỉ 30 phút)\n- Làm project thực tế > Chỉ đọc lý thuyết\n- Đừng sợ Google / Stack Overflow\n\nBạn muốn theo hướng nào? Tôi sẽ gợi ý chi tiết hơn! 💪", "conversation"),
        rec("Kể joke đi", "Đây nhé 😄\n\nProgrammer đi mua sữa:\n- Vợ: \"Đi mua 1 bịch sữa. Nếu có trứng thì mua 6.\"\n- Programmer mua 6 bịch sữa.\n- Vợ: \"Sao mua 6 bịch sữa?!\"\n- Programmer: \"Vì có trứng.\" 🥚\n\n---\n\nCòn cái này nữa:\n\n> Có 10 loại người trên thế giới: những người hiểu binary và những người không.\n\n😂 Bạn muốn nghe thêm không?", "conversation"),
        rec("Tôi chán quá, không biết làm gì", "Vài ý tưởng cho bạn:\n\n**Productive:**\n- Học skill mới trên YouTube\n- Viết blog hoặc journal\n- Dọn dẹp, sắp xếp workspace\n- Bắt đầu side project\n\n**Giải trí:**\n- Xem phim/series hay\n- Chơi game (Stardew Valley chill lắm)\n- Nghe podcast\n- Đọc sách\n\n**Thể chất:**\n- Đi bộ 30 phút\n- Nấu món mới\n- Tập thể dục nhẹ\n\nHoặc... cứ chat với tôi! Mình có thể bàn về bất kỳ topic nào bạn thích 😊", "conversation"),
        rec("Sáng mai tôi phải dậy sớm", "Vậy thì bạn nên chuẩn bị ngủ sớm! 🌙\n\n**Tips ngủ ngon:**\n1. Tắt điện thoại/laptop 30 phút trước khi ngủ\n2. Nhiệt độ phòng 22-25°C\n3. Đặt alarm + backup alarm\n4. Chuẩn bị sẵn quần áo, đồ cần mang\n\nCần tôi đặt reminder cho sáng mai không? Nói tôi giờ bạn muốn dậy!", "conversation"),
        rec("Thank you JARVIS", "You're welcome! 😊 Always happy to help. If you need anything else, I'm just a message away! Have a great day! 🙌", "conversation"),
    ]


def security_expanded() -> list[dict]:
    return [
        rec("SQL injection là gì và cách phòng chống?", "**SQL Injection** — chèn code SQL vào input:\n\n```\n# Vulnerable\nquery = f\"SELECT * FROM users WHERE name = '{user_input}'\"\n# Input: ' OR '1'='1\n# → SELECT * FROM users WHERE name = '' OR '1'='1'\n```\n\n**Phòng chống:**\n```python\n# ✅ Parameterized queries\ncursor.execute(\"SELECT * FROM users WHERE name = ?\", (user_input,))\n\n# ✅ ORM (SQLAlchemy)\nUser.query.filter_by(name=user_input).first()\n\n# ✅ Input validation\nimport re\nif not re.match(r'^[a-zA-Z0-9]+$', user_input):\n    raise ValueError(\"Invalid input\")\n```\n\n**Rule:** KHÔNG BAO GIỜ dùng f-string hoặc string concat cho SQL queries!", "security"),
        rec("XSS attack là gì?", "**XSS** (Cross-Site Scripting) — chèn JavaScript vào web page:\n\n**Loại:**\n1. **Stored XSS**: Script lưu trong DB, execute khi load page\n2. **Reflected XSS**: Script trong URL, execute khi click link\n3. **DOM XSS**: Client-side JS processing untrusted data\n\n**Ví dụ:**\n```html\n<!-- Vulnerable -->\n<p>Hello, {user_name}</p>\n<!-- Input: <script>alert('XSS')</script> -->\n```\n\n**Phòng chống:**\n- Escape HTML output (`&lt;` thay `<`)\n- Content Security Policy (CSP) headers\n- HttpOnly cookies (JS không đọc được)\n- Input sanitization\n- Dùng framework (React, Vue tự escape)", "security"),
        rec("HTTPS hoạt động thế nào?", "**HTTPS** = HTTP + TLS encryption:\n\n**TLS Handshake:**\n1. Client gửi \"Hello\" + supported ciphers\n2. Server chọn cipher + gửi certificate\n3. Client verify certificate (CA chain)\n4. Key exchange (Diffie-Hellman)\n5. Both sides derive session key\n6. Encrypted communication begins\n\n**Đảm bảo:**\n- **Confidentiality**: Data encrypted (AES-256)\n- **Integrity**: MAC verify data không bị sửa\n- **Authentication**: Certificate verify server identity\n\n**Setup:**\n```bash\n# Free SSL with Let's Encrypt\nsudo certbot --nginx -d mysite.com\n```", "security"),
        rec("JWT token hoạt động thế nào?", "**JWT** (JSON Web Token) — stateless authentication:\n\n**Cấu trúc:** `header.payload.signature`\n\n```\n# Header (base64)\n{\"alg\": \"HS256\", \"typ\": \"JWT\"}\n\n# Payload (base64)\n{\"sub\": \"user123\", \"exp\": 1709753600, \"role\": \"admin\"}\n\n# Signature\nHMAC-SHA256(header + \".\" + payload, secret_key)\n```\n\n**Flow:**\n1. User login → Server tạo JWT\n2. Client lưu JWT (localStorage/cookie)\n3. Mỗi request gửi: `Authorization: Bearer <token>`\n4. Server verify signature, check expiry\n\n**Best practices:**\n- Short expiry (15-30 min)\n- Refresh tokens for long sessions\n- KHÔNG lưu sensitive data trong payload", "security"),
    ]


def build_all() -> list[dict]:
    all_data = []
    generators = [
        math_advanced, analysis, factual_expanded, coding_patterns,
        devops_expanded, conversation_extended, security_expanded,
    ]
    for gen in generators:
        records = gen()
        all_data.extend(records)
        print(f"  {gen.__name__}: {len(records)} records")
    return all_data


def main():
    print("Building supplementary training data v3...")
    records = build_all()

    from collections import Counter
    cats = Counter(r["metadata"]["category"] for r in records)
    print(f"\nTotal: {len(records)} records across {len(cats)} categories")
    for cat, count in sorted(cats.items()):
        print(f"  {cat}: {count}")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"\nSaved to {OUTPUT}")


if __name__ == "__main__":
    main()
